version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - postgres-sync:/code
    ports:
      - "5432:5432"

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - django-sync:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  django-sync:
  postgres-sync: