#Docker-compose version
version: '3'

#services
services:

#Selenium Hub instance
  hub:
    image: selenium/hub:3
    ports:
      - 4444:4444

#Chrome node instance
  chrome:
    image: selenium/node-chrome:3
    links:
      - hub
  
  # web:
  #   build: .
  #   ports:
  #    - "5000:5000"
