#Docker-compose version
version: '3'

#services
services:

#Selenium Hub instance
  hub:
    image: selenium/hub:3
    ports:
      - 4444:4444

#Fire Fox node instance
  firefox:
    image: selenium/node-firefox:latest
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  db_development:
    image: postgres
    restart: always
    ports:
      - 5439:5432
    environment: 
      - POSTGRES_PASSWORD
      - DATABASE_OWNER
      - TEAM_PASSWORD
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8081
    volumes:
      - .:/app
    ports:
     - "5000:5000"
    depends_on:
      - db_development
    environment: 
      - PROJECT_NAME
      - DEBUG=True
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
